# =========================================================================================================
# code/diagnostics/build_site.R — assemble docs/index.html from the per-source table scripts in
#   code/diagnostics/tables/. Each tables/<asset>.R defines build_<asset>_section() returning one <section>
#   of HTML, built from data/raw with the same computations + curated content as the old CAA_Project
#   *_table.xlsx workbooks. This script sources them (in display order), concatenates the sections, and
#   writes the page. GitHub Pages serves docs/index.html directly; no build tool needed.
#   Reads data/raw directly (independent of cleaning/panels); a documentation step, not a data build.
# =========================================================================================================
library(here)
SRC <- here("code", "diagnostics", "tables")
source(file.path(SRC, "_html.R"))

# display order + nav labels
TITLES <- c(
  facilities = "ICIS-Air Facilities", violations = "ICIS-Air Violations",
  inspections = "ICIS-Air Compliance Monitoring", formal_actions = "ICIS-Air Formal Actions",
  informal_actions = "ICIS-Air Informal Actions", certs = "ICIS-Air Title V Certifications",
  stacktests = "ICIS-Air Stack Tests", pollutants = "ICIS-Air Pollutants", programs = "ICIS-Air Programs",
  program_subparts = "ICIS-Air Program Subparts", afs_actions = "AFS Actions",
  afs_air_program = "AFS Air Program", afs_facilities = "AFS Facilities",
  afs_hist_compliance = "AFS Historical Compliance", afs_hpv = "AFS HPV History",
  emissions = "Combined Emissions Report")

order <- names(TITLES)
skip  <- strsplit(Sys.getenv("SKIP_SECTIONS"), ",")[[1]]   # e.g. SKIP_SECTIONS=emissions to omit the 923MB read
order <- setdiff(order, skip)
for (a in order) { f <- file.path(SRC, paste0(a, ".R")); if (file.exists(f)) source(f) }

built <- list()
for (a in order) {
  fn <- paste0("build_", a, "_section")
  if (exists(fn, mode = "function")) {
    message("  building ", a)
    built[[a]] <- get(fn)()
  }
}

toc  <- paste0("<a href='#", names(built), "'>", esc(unname(TITLES[names(built)])), "</a>", collapse = "")
body <- paste(unlist(built), collapse = "\n")

css <- "
body{font-family:Calibri,'Segoe UI',system-ui,sans-serif;color:#1f2328;background:#fff;max-width:1100px;margin:0 auto;padding:2rem 1.2rem;}
h1{text-align:center;margin-bottom:.2rem;} .lead{text-align:center;color:#57606a;margin-top:0;}
nav{display:flex;flex-wrap:wrap;gap:.4rem .9rem;justify-content:center;margin:1.4rem 0 2rem;font-weight:bold;}
nav a{color:#0969da;text-decoration:none;} nav a:hover{text-decoration:underline;}
section{margin:2.6rem 0;padding-top:1rem;border-top:1px solid #e5e7eb;overflow-x:auto;}
h2{margin-bottom:.1rem;text-align:center;}
.src{text-align:center;color:#8a8f98;font-size:.85em;margin:.1rem 0;font-family:ui-monospace,Menlo,monospace;}
.desc{text-align:center;margin:.4rem auto .6rem;max-width:860px;}
.obs{text-align:center;font-weight:bold;margin:.3rem 0;}
.inv{text-align:center;color:#57606a;font-size:.84em;margin:.2rem auto 1rem;max-width:920px;}
table{border-collapse:collapse;width:100%;margin:.5rem 0 1rem;font-size:.9em;}
th,td{border:1px solid #9aa0a6;padding:5px 8px;text-align:center;vertical-align:middle;}
td.l{text-align:left;} .var{text-align:left;} .vd{font-weight:normal;color:#57606a;font-size:.92em;}
table.cat th{background:#C6EFCE;} table.num th{background:#F4B084;}
.note{font-size:.86em;color:#3d444d;margin:.35rem 0;line-height:1.4;}
.dupes{font-size:.9em;margin:1rem 0 .3rem;line-height:1.4;}
"

html <- paste0("<!doctype html><html lang='en'><head><meta charset='utf-8'>",
  "<meta name='viewport' content='width=device-width,initial-scale=1'>",
  "<title>CAA Regulatory Data — Summary Tables</title><style>", css, "</style></head><body>",
  "<h1>CAA Regulatory Data Infrastructure</h1>",
  "<p class='lead'>Per-source summary tables. Green = categorical (frequent values); orange = date / numeric distributions.</p>",
  "<nav>", toc, "</nav>", body,
  "<p style='text-align:center;color:#8a8f98;margin-top:3rem;font-size:.85em'>Generated by <code>code/diagnostics/build_site.R</code> from <code>data/raw/</code>.</p>",
  "</body></html>")

OUT <- here("docs", "index.html")
writeLines(html, OUT)
cat("wrote", OUT, "(", length(built), "of", length(order), "sections )\n")
