# =========================================================================================================
# code/diagnostics/site_shell.R \u2014 shared header/nav/hero/footer chrome + CSS design system for the public
#   docs/ site (Home, Raw Data, Databases). Sourced by each page's build script alongside
#   tables/_html.R (esc(), comma(), pct1(), dollar()). Contains NO computed numbers \u2014 chrome only.
# =========================================================================================================

NAV_ITEMS <- list(
  list(id = "home",      href = "index.html",     label = "Home"),
  list(id = "raw_data",  href = "raw_data.html",  label = "Raw Data"),
  list(id = "databases", href = "databases.html", label = "Databases")
)

site_nav <- function(active) {
  links <- vapply(NAV_ITEMS, function(n) {
    cls <- if (identical(n$id, active)) " class='active'" else ""
    sprintf("<a href='%s'%s>%s</a>", n$href, cls, esc(n$label))
  }, character(1))
  paste0("<nav class='site-nav'>", paste(links, collapse = ""), "</nav>")
}

site_header <- function(active) paste0(
  "<header class='site-header'><div class='site-header-inner'>",
  "<a class='site-brand' href='index.html'>CAA Regulatory Data</a>",
  site_nav(active),
  "</div></header>")

# eyebrow: small caps label above the title (optional). title/desc: plain text, escaped here.
hero <- function(title, desc = NULL, eyebrow = NULL) paste0(
  "<div class='hero'><div class='hero-inner'>",
  if (!is.null(eyebrow)) paste0("<p class='eyebrow'>", esc(eyebrow), "</p>") else "",
  "<h1>", esc(title), "</h1>",
  if (!is.null(desc)) paste0("<p>", esc(desc), "</p>") else "",
  "</div></div>")

page_main <- function(...) paste0("<main>", paste0(..., collapse = ""), "</main>")

card <- function(title, desc, href, cta = "View \u2192") paste0(
  "<div class='card'><h3>", esc(title), "</h3><p>", esc(desc), "</p>",
  "<a href='", href, "'>", esc(cta), "</a></div>")

cards <- function(...) paste0("<div class='cards'>", paste0(..., collapse = ""), "</div>")

site_footer <- function(script) paste0(
  "<footer class='site-footer'><p>Generated by <code>", esc(script), "</code> \u2014 part of the ",
  "<a href='https://github.com/gracecarverr/caa-regdata'>caa-regdata</a> reproducible pipeline.</p></footer>")

# title: page title (used in <title> + meta); description: one-line meta description (plain text);
# active: one of NAV_ITEMS[[i]]$id; body_html: hero() + page_main(...) already assembled by the caller;
# script: generating script path, shown in the footer.
site_shell <- function(title, description, active, body_html, script = "code/diagnostics/") paste0(
  "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
  "<meta name='viewport' content='width=device-width,initial-scale=1'>",
  "<title>", esc(title), " \u2014 CAA Regulatory Data</title>",
  if (!is.null(description)) paste0("<meta name='description' content=\"", esc(description), "\">") else "",
  "<style>", SITE_CSS, "</style></head><body>",
  site_header(active),
  body_html,
  site_footer(script),
  "</body></html>")

# ---- design system -------------------------------------------------------------------------------------
# Navy hero bands + serif display headlines + muted burgundy accent, EPIC-leaning. System-sans body type
# retained for the dense data tables (legibility over thematic purity there). The raw-data page's existing
# table styling (.cat/.num headers, etc.) is scoped under .raw-data so it can't collide with this chrome.
SITE_CSS <- "
:root{
  --navy:#1c2b4a; --navy-dark:#12192e; --accent:#7a2530; --gold:#b5793a;
  --bg:#f7f5f1; --ink:#1f2328; --muted:#57606a; --border:#e2ddd3;
}
*{box-sizing:border-box;}
body{margin:0;font-family:Calibri,'Segoe UI',system-ui,sans-serif;color:var(--ink);background:var(--bg);}
a{color:var(--accent);}

.site-header{background:#fff;border-bottom:1px solid var(--border);}
.site-header-inner{max-width:1100px;margin:0 auto;padding:.9rem 1.2rem;display:flex;align-items:center;
  justify-content:space-between;flex-wrap:wrap;gap:.5rem 1.2rem;}
.site-brand{font-family:Georgia,'Iowan Old Style','Palatino Linotype',serif;font-weight:700;font-size:1.2rem;
  color:var(--navy);text-decoration:none;letter-spacing:.01em;}
.site-nav{display:flex;gap:1.5rem;font-weight:600;font-size:.92rem;flex-wrap:wrap;}
.site-nav a{color:var(--accent);text-decoration:none;padding:.15rem 0;border-bottom:2px solid transparent;}
.site-nav a:hover{border-bottom-color:var(--accent);}
.site-nav a.active{color:var(--navy);border-bottom-color:var(--gold);}

.hero{background:linear-gradient(160deg,var(--navy) 0%,var(--navy-dark) 100%);color:#fff;
  padding:3rem 1.2rem 2.4rem;}
.hero-inner{max-width:1100px;margin:0 auto;}
.hero .eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:.76rem;color:#cba867;font-weight:700;
  margin:0 0 .7rem;}
.hero h1{font-family:Georgia,'Iowan Old Style','Palatino Linotype',serif;font-weight:500;font-size:2.5rem;
  line-height:1.18;margin:0 0 .7rem;}
.hero p{font-size:1.05rem;max-width:760px;color:#dde1ec;margin:0;line-height:1.55;}

main{max-width:1100px;margin:0 auto;padding:2.4rem 1.2rem 3rem;}

.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1.1rem;margin:1.6rem 0 2.4rem;}
.card{border:1px solid var(--border);border-top:3px solid var(--navy);background:#fff;padding:1.2rem 1.3rem;}
.card h3{font-family:Georgia,'Iowan Old Style',serif;margin:.1rem 0 .4rem;font-size:1.15rem;color:var(--navy);}
.card p{font-size:.92rem;color:var(--muted);margin:0 0 .8rem;line-height:1.45;}
.card a{color:var(--accent);font-weight:600;font-size:.88rem;text-decoration:none;}
.card a:hover{text-decoration:underline;}

.prose h2{font-family:Georgia,'Iowan Old Style',serif;color:var(--navy);border-top:1px solid var(--border);
  padding-top:1.6rem;margin-top:2.4rem;font-size:1.5rem;text-align:left;}
.prose h2:first-child{border-top:none;padding-top:0;margin-top:0;}
.prose h3{font-family:Georgia,'Iowan Old Style',serif;color:var(--navy);margin-top:1.7rem;font-size:1.18rem;}
.prose p,.prose li{line-height:1.62;}
.prose blockquote{border-left:3px solid var(--gold);margin:1.1rem 0;padding:.35rem 1.1rem;color:var(--muted);
  background:#fbf8f2;}
.prose table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:.92em;}
.prose th,.prose td{border:1px solid var(--border);padding:.5rem .7rem;text-align:left;vertical-align:top;}
.prose th{background:#eef0f4;}
.prose code{font-family:ui-monospace,Menlo,monospace;background:#eef0f4;padding:.05rem .3rem;font-size:.9em;}

.section-note{background:#fbf8f2;border:1px solid var(--border);border-left:3px solid var(--gold);
  padding:.9rem 1.1rem;margin:1.4rem 0;font-size:.92em;line-height:1.55;}

.stat-table{border-collapse:collapse;width:100%;margin:.6rem 0 .5rem;font-size:.9em;}
.stat-table th,.stat-table td{border:1px solid var(--border);padding:.45rem .7rem;text-align:right;}
.stat-table th{background:var(--navy);color:#fff;font-weight:600;text-align:right;}
.stat-table td:first-child,.stat-table th:first-child{text-align:left;}
.stat-table caption{caption-side:top;text-align:left;font-weight:700;color:var(--navy);
  font-family:Georgia,'Iowan Old Style',serif;font-size:1.15rem;margin:2rem 0 .4rem;}
.stat-table caption:first-of-type{margin-top:.4rem;}
.table-note{font-size:.85em;color:var(--muted);margin:-.1rem 0 1.8rem;line-height:1.5;}

.site-footer{border-top:1px solid var(--border);margin-top:1rem;padding:1.4rem 1.2rem;text-align:center;
  color:var(--muted);font-size:.82rem;}
.site-footer code{font-family:ui-monospace,Menlo,monospace;background:#eef0f4;padding:.1rem .35rem;}

/* ---- raw-data page: scoped table styling (unchanged rules from the original docs/index.html) -------- */
.raw-data h1{text-align:center;margin-bottom:.2rem;font-family:Georgia,'Iowan Old Style',serif;}
.raw-data .lead{text-align:center;color:var(--muted);margin-top:0;}
.raw-data .section-toc{display:flex;flex-wrap:wrap;gap:.4rem .9rem;justify-content:center;margin:1.4rem 0 2rem;
  font-weight:bold;}
.raw-data .section-toc a{color:#0969da;text-decoration:none;}
.raw-data .section-toc a:hover{text-decoration:underline;}
.raw-data section{margin:2.6rem 0;padding-top:1rem;border-top:1px solid var(--border);overflow-x:auto;}
.raw-data h2{margin-bottom:.1rem;text-align:center;font-family:Georgia,'Iowan Old Style',serif;color:var(--navy);}
.raw-data .src{text-align:center;color:#8a8f98;font-size:.85em;margin:.1rem 0;font-family:ui-monospace,Menlo,monospace;}
.raw-data .desc{text-align:center;margin:.4rem auto .6rem;max-width:860px;}
.raw-data .obs{text-align:center;font-weight:bold;margin:.3rem 0;}
.raw-data .inv{text-align:center;color:var(--muted);font-size:.84em;margin:.2rem auto 1rem;max-width:920px;}
.raw-data table{border-collapse:collapse;width:100%;margin:.5rem 0 1rem;font-size:.9em;}
.raw-data th,.raw-data td{border:1px solid #9aa0a6;padding:5px 8px;text-align:center;vertical-align:middle;}
.raw-data td.l{text-align:left;} .raw-data .var{text-align:left;}
.raw-data .vd{font-weight:normal;color:var(--muted);font-size:.92em;}
.raw-data table.cat th{background:#C6EFCE;} .raw-data table.num th{background:#F4B084;}
.raw-data .note{font-size:.86em;color:#3d444d;margin:.35rem 0;line-height:1.4;}
.raw-data .dupes{font-size:.9em;margin:1rem 0 .3rem;line-height:1.4;}

@media (max-width:700px){
  .hero h1{font-size:1.9rem;}
  .site-header-inner{flex-direction:column;align-items:flex-start;}
  .site-nav{gap:.9rem;font-size:.85rem;}
}
"
