# =========================================================================================================
# scripts/03_document.R -- generate the documentation from the clean assets.
#   Writes docs/dictionary.md and docs/distributions.md (COMMITTED, human-readable Markdown), so they render
#   directly on GitHub and in the Quarto site with no build step. Regenerate any time with run_all.R.
# =========================================================================================================
source(here::here("R/document.R"))

banner <- "<!-- GENERATED by scripts/03_document.R from data/clean/ -- do not edit; regenerate with run_all.R -->"

# ---- data dictionary ----------------------------------------------------------------------------------
dict <- collect_dictionary()
dict_body <- unlist(lapply(sort(unique(dict$asset)), function(a) {
  c(sprintf("## %s", a), "", md_table(dict[dict$asset == a, c("column", "definition")]), "")
}))
writeLines(c(banner, "", "# Data Dictionary", "",
             "Every column of every clean asset, defined -- generated from the dictionary each cleaner",
             "registers via `write_asset()`, so it always matches the data.", "", dict_body),
           here::here("docs/dictionary.md"))

# ---- variable distributions ---------------------------------------------------------------------------
dist_body <- unlist(lapply(sort(list_assets()), function(a) {
  cat(" - distributions:", a, "\n")
  c(sprintf("## %s", a), "", md_table(variable_distributions(a)), "")
}))
writeLines(c(banner, "", "# Variable Distributions", "",
             "Per-variable summaries for each clean asset -- row counts, missingness, distinct values, and a",
             "type-aware summary -- generated from `data/clean/`.", "", dist_body),
           here::here("docs/distributions.md"))

cat("wrote docs/dictionary.md and docs/distributions.md\n")
